### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by josepharhar** [josepharhar/tcp#1]
- [x] Create library to be linked with other programs
- [x] Create example program to use library (curl/wget like)
- [x] Support simple HTTP requests over a reliable connection
- [x] Support large (multi-packet) HTTP requests
- [ ] Support unreliable connections
- [x] Make requests to real web servers on the internet (users.csc.calpoly.edu)
- [ ] Use random available port
